### PR TITLE
Code review for Velludo and Turcato (pt.2)

### PR DESCRIPTION
**Pull request by tonin-alessandra**
Per riconoscere il codice da revisionare ho inserito nell'@author dei file "CODE REVIEW FOR VELLUDO AND TURCATO".

### CODE REVIEW

**Comment by turcato-niccolo** [comment]
This is good and clean code overall, nice!

I have some tips:

-This method of RingtoneHandler (line 34) 
`public static Ringtone getDefaultTone(Context ctx, int type)`
Should be private in my opinion, since it gives to RingtoneManager a parameter that is one of its constants, and you're wrapping the class.

- `static void playRingtone(@NonNull Ringtone ringtone, final int USAGE_CODE)` (line 68)
This method takes the parameter USAGE_CODE, that is a constant from AudioAttributes, and I wouldn't quite like it if I were you. Instead, I would define some constants inside of this class that are essentially a copy of the ones you need from AudioAttributes. So that who uses RingtoneHandler doesn't have to access AudioAttributes at all.
There might be better ways, this is the only one I have in my mind right now.

Nothing else here, keep up the good work!

**Comment by giovannivelludo** [comment]
What's the point of having two different packages for two single classes?

**MainActivity.java**

lines 39, 53, 65
Verb "to click" is used in its past tense, should be "is clicked" instead.

**RingtoneHandler.java**

line 34
getDefaultTone() is used only in this class, if there's no need to use it outside of RingtoneHandler, then it should be set to private.
Missing description of parameter type, can it be any integer?

line 63
Is the user always a male?

line 68
playRingtone() is used only in this class, if there's no need to use it outside of RingtoneHandler, then it should be set to private.

line 74
"di" is not an English word.

**Comment by tonin-alessandra** [comment]
@giovannivelludo, I checked what you said about lines 33, 34 in MainActivity.java: if the user exits the app, changes the default ringtone and then returns to the app (without closing and restarting it), the new ringtone will be played, not the old one.

**Comment by giovannivelludo** [comment]
Thanks! Since onCreate() is executed only when the activity is created, and not when it is resumed, I thought RingtoneManager.getRingtone() would return a reference to a specific ringtone, and not to the default ringtone regardless of what ringtone it actually is.

**Comment by tonin-alessandra** [comment]
@turcato-niccolo I think what you said about USAGE_CODE is not necessary because who uses RingtoneHandler has to access AudioAttributes in any case, to set them in _ringtone.setAudioAttributes(...)_

**Pull request merged**
